"""Render Docker Compose files from evaluated Pkl config objects."""

from __future__ import annotations

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
import io


GENERATED_HEADER = "# Generated by tools/generate_configs.py — DO NOT EDIT\n"


def render_compose(cfg) -> str:
    """Render a docker-compose.yml from the Pkl config model."""
    rt = cfg.runtime
    ct = cfg.container
    cp = cfg.compose
    dep = cfg.deployment

    service = CommentedMap()

    # Build config
    build = CommentedMap()
    build["context"] = "."
    build["dockerfile"] = "Dockerfile"
    build_args = CommentedMap()
    build_args["IBCTL_BUILD_VERSION"] = "${IBCTL_BUILD_VERSION:-}"
    build["args"] = build_args
    service["build"] = build

    service["container_name"] = ct.containerName
    service["restart"] = ct.restartPolicy
    service["oom_score_adj"] = -1000

    # Environment
    env = CommentedMap()
    env["DISPLAY"] = ":1"

    # Auth
    env["TWS_USERID"] = "${TWS_USERID}"
    env["TWS_PASSWORD"] = "${TWS_PASSWORD}"
    env["TWS_USERID_PAPER"] = "${TWS_USERID_PAPER:-}"
    env["TWS_PASSWORD_PAPER"] = "${TWS_PASSWORD_PAPER:-}"

    # Trading mode
    mode = dep.tradingMode
    env["TRADING_MODE"] = f"${{TRADING_MODE:-{mode}}}"

    # 2FA
    env["TWOFA_DEVICE"] = "${TWOFA_DEVICE:-}"
    env["TWOFA_TIMEOUT_ACTION"] = (
        f"${{TWOFA_TIMEOUT_ACTION:-{rt.twofa.timeoutAction}}}"
    )
    env["TWOFA_EXIT_INTERVAL"] = (
        f"${{TWOFA_EXIT_INTERVAL:-{int(rt.twofa.timeoutSeconds)}}}"
    )
    env["RELOGIN_AFTER_TWOFA_TIMEOUT"] = "${RELOGIN_AFTER_TWOFA_TIMEOUT:-yes}"

    # API
    env["TWS_ACCEPT_INCOMING"] = (
        f"${{TWS_ACCEPT_INCOMING:-{rt.session.acceptIncoming}}}"
    )
    env["TWS_MASTER_CLIENT_ID"] = "${TWS_MASTER_CLIENT_ID:-}"
    env["READ_ONLY_API"] = "${READ_ONLY_API:-no}"
    env["BYPASS_WARNING"] = "${BYPASS_WARNING:-yes}"
    env["ALLOW_BLIND_TRADING"] = "${ALLOW_BLIND_TRADING:-no}"

    # Scheduling
    env["AUTO_RESTART_TIME"] = "${AUTO_RESTART_TIME:-09:05 PM}"
    env["TWS_COLD_RESTART"] = "${TWS_COLD_RESTART:-}"

    # Gateway
    env["JAVA_HEAP_SIZE"] = f"${{JAVA_HEAP_SIZE:-{int(rt.gateway.javaHeapMb)}}}"
    env["TZ"] = f"${{TZ:-{dep.timezone}}}"
    env["VNC_SERVER_PASSWORD"] = "${VNC_SERVER_PASSWORD:-}"
    env["RUST_LOG"] = "${RUST_LOG:-ibctl=info}"
    env["IBCTL_LOG_DIR"] = "/opt/ibctl/persist/logs"

    # Dashboard
    dash_enabled = "true" if ct.enableDashboard else "false"
    env["IBCTL_DASHBOARD_ENABLED"] = (
        f"${{IBCTL_DASHBOARD_ENABLED:-{dash_enabled}}}"
    )
    env["IBCTL_DASHBOARD_PORT"] = (
        f"${{IBCTL_DASHBOARD_PORT:-{int(rt.dashboard.port)}}}"
    )
    env["IBCTL_DASHBOARD_TOKEN"] = "${IBCTL_DASHBOARD_TOKEN:-}"
    env["IBCTL_ROOT_PATH"] = "${IBCTL_ROOT_PATH:-}"
    env["IBCTL_DEBUG_MODE"] = "${IBCTL_DEBUG_MODE:-false}"
    env["IBCTL_COMMAND_HOST"] = "${IBCTL_COMMAND_HOST:-127.0.0.1}"
    env["IBCTL_COMMAND_PORT"] = (
        f"${{IBCTL_COMMAND_PORT:-{int(rt.commandServer.port)}}}"
    )
    env["IBCTL_COMMAND_HOST_PAPER"] = "${IBCTL_COMMAND_HOST_PAPER:-127.0.0.1}"
    env["IBCTL_COMMAND_PORT_PAPER"] = (
        f"${{IBCTL_COMMAND_PORT_PAPER:-{int(rt.commandServer.paperPort)}}}"
    )

    # Notifications
    env["IBCTL_NOTIFICATIONS_ENABLED"] = "${IBCTL_NOTIFICATIONS_ENABLED:-false}"
    env["IBCTL_NTFY_URL"] = "${IBCTL_NTFY_URL:-}"
    env["IBCTL_NTFY_TOPIC"] = "${IBCTL_NTFY_TOPIC:-}"
    env["IBCTL_NTFY_TOKEN"] = "${IBCTL_NTFY_TOKEN:-}"

    # IB Status
    env["IB_STATUS_CHECK_INTERVAL"] = (
        f"${{IB_STATUS_CHECK_INTERVAL:-{int(rt.ibSystemStatus.checkIntervalSeconds)}}}"
    )
    env["IB_STATUS_REGION"] = f"${{IB_STATUS_REGION:-{rt.ibSystemStatus.region}}}"

    # Auto-update
    env["IBCTL_AUTO_UPDATE"] = "${IBCTL_AUTO_UPDATE:-false}"
    env["IBCTL_VERSION"] = "${IBCTL_VERSION:-latest}"

    service["environment"] = env

    # Volumes
    volumes = CommentedSeq()
    volumes.append(f"{cp.persistVolumeName}:{cp.persistMountPath}")
    service["volumes"] = volumes

    # Ports
    ports = CommentedSeq()
    if cp.exposeLiveApi:
        ports.append(
            f"${{IBCTL_LIVE_API_BIND:-127.0.0.1}}:${{IBCTL_LIVE_API_PORT:-4001}}:"
            f"{int(rt.gateway.liveSocatPort)}"
        )
    if cp.exposePaperApi:
        ports.append(
            f"${{IBCTL_PAPER_API_BIND:-127.0.0.1}}:${{IBCTL_PAPER_API_PORT:-4002}}:"
            f"{int(rt.gateway.paperSocatPort)}"
        )
    if cp.exposeVnc:
        ports.append("${IBCTL_VNC_BIND:-127.0.0.1}:5900:5900")
    if cp.exposeNoVnc:
        ports.append("${IBCTL_VNC_BIND:-127.0.0.1}:6080:6080")
    if cp.exposeCommandServer:
        ports.append(f"127.0.0.1:{int(rt.commandServer.port)}:{int(rt.commandServer.port)}")
    if cp.exposePaperCommandServer:
        ports.append(
            f"127.0.0.1:{int(rt.commandServer.paperPort)}:{int(rt.commandServer.paperPort)}"
        )
    if cp.exposeDashboard:
        # Both sides use the same env var default — matches canonical docker-compose.yml
        ports.append(
            "${IBCTL_DASHBOARD_BIND:-127.0.0.1}:${IBCTL_DASHBOARD_PORT:-3080}:"
            "${IBCTL_DASHBOARD_PORT:-3080}"
        )
    service["ports"] = ports
    service["tty"] = True

    # Top-level
    root = CommentedMap()
    services = CommentedMap()
    services[cp.serviceName] = service
    root["services"] = services

    # Named volumes
    named_volumes = CommentedMap()
    named_volumes[cp.persistVolumeName] = None
    root["volumes"] = named_volumes

    yaml = YAML()
    yaml.default_flow_style = False
    yaml.width = 120

    buf = io.StringIO()
    yaml.dump(root, buf)
    return GENERATED_HEADER + buf.getvalue()
