"""Render .env.example from evaluated Pkl config objects."""

from __future__ import annotations


def render_env_example(cfg) -> str:
    """Render a documented .env.example from the Pkl config model."""
    dep = cfg.deployment
    rt = cfg.runtime

    lines = [
        "# Generated by tools/generate_configs.py — DO NOT EDIT",
        "# ibctl environment configuration",
        "# Copy to .env and fill in your credentials.",
        "# NEVER commit .env to version control.",
        "",
        "# Authentication",
        "TWS_USERID=your_username",
        "TWS_PASSWORD=your_password",
        f"TRADING_MODE={dep.tradingMode}                # live | paper | both",
        "",
        "# Paper mode (only needed for TRADING_MODE=both)",
        "TWS_USERID_PAPER=your_paper_username",
        "TWS_PASSWORD_PAPER=your_paper_password",
        "",
        "# Two-factor authentication",
        "TWOFA_DEVICE=IB Key               # or \"Mobile Authenticator app\"",
        f"TWOFA_TIMEOUT_ACTION={rt.twofa.timeoutAction}       # restart | exit",
        f"TWOFA_EXIT_INTERVAL={int(rt.twofa.timeoutSeconds)}",
        "RELOGIN_AFTER_TWOFA_TIMEOUT=yes",
        "",
        "# Session",
        f"EXISTING_SESSION_DETECTED_ACTION={rt.session.action}",
        "",
        "# API configuration (applied after login)",
        f"TWS_ACCEPT_INCOMING={rt.session.acceptIncoming}",
        "TWS_MASTER_CLIENT_ID=50",
        "READ_ONLY_API=no",
        "BYPASS_WARNING=yes",
        "ALLOW_BLIND_TRADING=no",
        "",
        "# Scheduling",
        "AUTO_RESTART_TIME=05:05 PM",
        "TWS_COLD_RESTART=09:00",
        "",
        "# Gateway",
        f"JAVA_HEAP_SIZE={int(rt.gateway.javaHeapMb)}",
        f"TZ={dep.timezone}",
        "",
        "# VNC (optional — set password to enable)",
        "VNC_SERVER_PASSWORD=",
        "",
        "# Logging",
        f"RUST_LOG=ibctl={rt.logging.level}",
        "",
    ]

    return "\n".join(lines) + "\n"
