"""Render ibctl TOML config files from evaluated Pkl config objects.

Two output modes:
- docker_toml: Full deployment defaults (docker/ibctl.toml) with all sections.
- example_toml: User-facing template (ibctl.toml.example) with guidance comments.
"""

from __future__ import annotations

import tomlkit


def _listing_to_list(obj) -> list:
    """Convert a Pkl Listing (or Python list) to a plain list."""
    if isinstance(obj, list):
        return obj
    # pkl-python may return lists directly; handle iterables
    try:
        return list(obj)
    except TypeError:
        return []


def render_docker_toml(cfg) -> str:
    """Render docker/ibctl.toml — rich deployment defaults with all sections.

    This matches the current docker/ibctl.toml layout and comments.
    """
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by tools/generate_configs.py — DO NOT EDIT"))
    doc.add(tomlkit.comment("ibctl configuration — defaults for Docker deployment"))
    doc.add(
        tomlkit.comment(
            "Override any value via environment variables (see docs/CLIENT_INTEGRATION_GUIDE.md)."
        )
    )
    doc.add(
        tomlkit.comment(
            "Passwords/secrets are NEVER in this file — use env vars (TWS_PASSWORD, etc.)"
        )
    )
    doc.add(tomlkit.nl())

    rt = cfg.runtime

    # [auth]
    auth = tomlkit.table()
    auth.add(tomlkit.comment("set via TWS_USERID env var"))
    auth.add("tws_userid", rt.auth.twsUserid)
    auth.add(tomlkit.comment('"live", "paper", or "both"'))
    auth.add("trading_mode", rt.auth.tradingMode)
    auth.add(tomlkit.comment("Paper credentials (for TRADING_MODE=both):"))
    auth.add(tomlkit.comment('paper.tws_userid = ""    # set via TWS_USERID_PAPER env var'))
    doc.add("auth", auth)
    doc.add(tomlkit.nl())

    # [twofa]
    twofa = tomlkit.table()
    twofa.add(
        tomlkit.comment(
            '"oathtool" (shells out) or "builtin" (not yet implemented)'
        )
    )
    twofa.add("provider", rt.twofa.provider)
    twofa.add(tomlkit.comment("name of env var holding TOTP secret"))
    _secret_env = tomlkit.item(rt.twofa.secretEnv)
    _secret_env.comment("pragma: allowlist secret")
    twofa.add("secret_env", _secret_env)
    twofa.add(tomlkit.comment('"restart" (re-login) or "exit" (shutdown)'))
    twofa.add("timeout_action", rt.twofa.timeoutAction)
    twofa.add(tomlkit.comment("max wait for 2FA approval before timeout_action"))
    twofa.add("exit_interval", int(rt.twofa.exitInterval))
    twofa.add(tomlkit.comment("2FA device name for device selection dialog (empty = skip)"))
    twofa.add("device", rt.twofa.device)
    twofa.add(tomlkit.comment("force re-login even if timeout_action != restart"))
    twofa.add("relogin_after_timeout", rt.twofa.reloginAfterTimeout)

    # [twofa.backoff] — HITL 2FA policy (nested sub-section)
    backoff = tomlkit.table()
    backoff.add(
        tomlkit.comment(
            "Max consecutive 2FA timeouts before entering WaitingForHitl2fa"
        )
    )
    backoff.add("max_immediate_attempts", int(rt.twofa.backoff.maxImmediateAttempts))
    backoff.add(
        tomlkit.comment(
            'Action on 2FA timeout: "restart_then_hitl" | "restart_forever" | "hitl_immediately"'
        )
    )
    backoff.add("on_timeout", rt.twofa.backoff.onTimeout)
    backoff.add(
        tomlkit.comment(
            'HITL resume strategy: "disabled" | "periodic" | "ntfy_callback" | "both"'
        )
    )
    backoff.add("strategy", rt.twofa.backoff.strategy)
    backoff.add(tomlkit.comment("retry cadence (minutes); list traversed then held at last"))
    backoff.add(
        "intervals_minutes",
        [int(m) for m in _listing_to_list(rt.twofa.backoff.intervalsMinutes)],
    )
    backoff.add(tomlkit.comment("hours the signed ntfy-action URL stays valid (one-shot)"))
    backoff.add("callback_valid_hours", int(rt.twofa.backoff.callbackValidHours))
    backoff.add(tomlkit.comment('when to reset attempt counter: "any_reach" | "stable"'))
    backoff.add("counter_reset", rt.twofa.backoff.counterReset)
    backoff.add(tomlkit.comment("seconds Connected must persist under counter_reset=stable"))
    backoff.add("stable_secs", int(rt.twofa.backoff.stableSecs))
    backoff.add(tomlkit.comment("cold restart preempts HITL; false defers cold restart"))
    backoff.add("cold_restart_preempts_hitl", rt.twofa.backoff.coldRestartPreemptsHitl)
    backoff.add(tomlkit.comment("retries for initial ntfy send failure (0 = give up silently)"))
    backoff.add("ntfy_send_retries", int(rt.twofa.backoff.ntfySendRetries))
    twofa.add("backoff", backoff)
    doc.add("twofa", twofa)
    doc.add(tomlkit.nl())

    # [gateway]
    gw = tomlkit.table()
    gw.add("tws_path", rt.gateway.twsPath)
    gw.add(tomlkit.comment("empty = use tws_path"))
    gw.add("tws_settings_path", rt.gateway.twsSettingsPath)
    gw.add(tomlkit.comment("auto-detected from TWS_MAJOR_VRSN env var"))
    gw.add("tws_major_vrsn", rt.gateway.twsMajorVrsn)
    gw.add("java_heap_size", int(rt.gateway.javaHeapSize))
    gw.add(tomlkit.comment('"gateway" or "tws"'))
    gw.add("gateway_or_tws", rt.gateway.gatewayOrTws)
    gw.add(
        tomlkit.comment(
            "API and socat port mappings (Gateway listens on api port, socat forwards from socat port)"
        )
    )
    gw.add("live_api_port", int(rt.gateway.liveApiPort))
    gw.add("paper_api_port", int(rt.gateway.paperApiPort))
    gw.add("live_socat_port", int(rt.gateway.liveSocatPort))
    gw.add("paper_socat_port", int(rt.gateway.paperSocatPort))
    doc.add("gateway", gw)
    doc.add(tomlkit.nl())

    # [session]
    sess = tomlkit.table()
    sess.add(tomlkit.comment('"primary", "secondary", or "primaryoverride"'))
    sess.add("action", rt.session.action)
    sess.add(tomlkit.comment('"accept", "reject", or "manual"'))
    sess.add("accept_incoming", rt.session.acceptIncoming)
    sess.add(tomlkit.comment('"HH:MM" 24h format for Sunday cold restart (empty = disabled)'))
    sess.add("tws_cold_restart", rt.session.twsColdRestart)
    sess.add(
        tomlkit.comment(
            "Cold restart day of week: 0=Sunday, 1=Monday, ..., 6=Saturday"
        )
    )
    sess.add("tws_cold_restart_day", int(rt.session.twsColdRestartDay))
    doc.add("session", sess)
    doc.add(tomlkit.nl())

    # [command_server]
    cs = tomlkit.table()
    cs.add("enabled", rt.commandServer.enabled)
    cs.add(tomlkit.comment("live instance command server port"))
    cs.add("port", int(rt.commandServer.port))
    cs.add(tomlkit.comment("paper instance command server port"))
    cs.add("paper_port", int(rt.commandServer.paperPort))
    cs.add("bind_address", rt.commandServer.bindAddress)
    cs.add("control_from", _listing_to_list(rt.commandServer.controlFrom))
    doc.add("command_server", cs)
    doc.add(tomlkit.nl())

    # [agent]
    agent = tomlkit.table()
    agent.add("socket_path", rt.agent.socketPath)
    doc.add("agent", agent)
    doc.add(tomlkit.nl())

    # [ib_status] — ibctl-side policy for IBSTATUS pushes
    ibs_policy = tomlkit.table()
    ibs_policy.add(
        tomlkit.comment(
            "When IBSTATUS=unavailable arrives, should ibctl kick a Connected session?"
        )
    )
    ibs_policy.add(
        tomlkit.comment(
            "Default false — IBSTATUS gates login retry, not active sessions."
        )
    )
    ibs_policy.add("kick_active_session", rt.ibStatus.kickActiveSession)
    doc.add("ib_status", ibs_policy)
    doc.add(tomlkit.nl())

    # [dashboard]
    dash = tomlkit.table()
    dash.add(
        tomlkit.comment("set IBCTL_DASHBOARD_ENABLED=true to start the web dashboard")
    )
    dash.add("enabled", rt.dashboard.enabled)
    dash.add("port", int(rt.dashboard.port))
    dash.add(tomlkit.comment("Bearer token for API auth (empty = no auth)"))
    dash.add("token", rt.dashboard.token)
    dash.add(tomlkit.comment("enable debug endpoints"))
    dash.add("debug_mode", rt.dashboard.debugMode)
    dash.add(tomlkit.nl())
    dash.add(
        tomlkit.comment("OAuth/SSO (requires dashboard.enabled — secrets are env-only)")
    )
    dash.add(
        tomlkit.comment(
            "GitHub OAuth: set IBCTL_GITHUB_OAUTH_CLIENT_ID + _CLIENT_SECRET env vars"
        )
    )
    dash.add("github_oauth_enabled", rt.dashboard.githubOauthEnabled)
    dash.add(
        tomlkit.comment(
            "OIDC/SSO (Authentik, Keycloak): set IBCTL_OIDC_CLIENT_ID + _CLIENT_SECRET env vars"
        )
    )
    dash.add("oidc_enabled", rt.dashboard.oidcEnabled)
    dash.add(tomlkit.comment("OIDC issuer URL (env: IBCTL_OIDC_ISSUER)"))
    dash.add("oidc_issuer", rt.dashboard.oidcIssuer)
    dash.add(tomlkit.comment("OIDC scopes (env: IBCTL_OIDC_SCOPES)"))
    dash.add("oidc_scopes", rt.dashboard.oidcScopes)
    dash.add(tomlkit.nl())
    dash.add(
        tomlkit.comment(
            "Notifications (ntfy, Slack, Telegram — requires dashboard.enabled)"
        )
    )
    dash.add("notifications_enabled", rt.dashboard.notificationsEnabled)
    dash.add(
        tomlkit.comment(
            "Notification channel: ntfy | slack | telegram (env: IBCTL_NOTIFICATION_CHANNEL)"
        )
    )
    dash.add("notification_channel", rt.dashboard.notificationChannel)
    dash.add(tomlkit.nl())
    dash.add(
        tomlkit.comment(
            "ZMQ PUB socket for external status subscribers (env: IBCTL_ZMQ_ENABLED)"
        )
    )
    dash.add("zmq_enabled", rt.dashboard.zmqEnabled)
    dash.add(tomlkit.comment("ZMQ PUB port (env: IBCTL_ZMQ_PORT)"))
    dash.add("zmq_port", int(rt.dashboard.zmqPort))
    doc.add("dashboard", dash)
    doc.add(tomlkit.nl())

    # [ib_system_status]
    ibs = tomlkit.table()
    ibs.add("enabled", rt.ibSystemStatus.enabled)
    ibs.add(
        tomlkit.comment(
            "fail-open TTL: if no status push within this period, assume available"
        )
    )
    ibs.add("ttl_seconds", int(rt.ibSystemStatus.ttlSeconds))
    ibs.add(
        tomlkit.comment(
            "Scraper settings (read by dashboard daemon, configurable via env vars too):"
        )
    )
    ibs.add(
        tomlkit.comment(
            f'check_interval = {int(rt.ibSystemStatus.checkIntervalSeconds)}'
            '     # seconds between IB status page scrapes (default 5 min)'
        )
    )
    ibs.add(
        tomlkit.comment(
            f'url = "{rt.ibSystemStatus.url}"'
        )
    )
    ibs.add(
        tomlkit.comment(
            f'region = "{rt.ibSystemStatus.region}"'
            '            # "NA", "EU", or "APAC" — which maintenance windows to monitor'
        )
    )
    backend_hosts_str = ",".join(_listing_to_list(rt.ibSystemStatus.backendHosts))
    ibs.add(
        tomlkit.comment(
            f'backend_hosts = "{backend_hosts_str}"'
            "  # IB backend servers (checked via TCP probe)"
        )
    )
    ibs.add(
        tomlkit.comment(
            f'fallback_host = "{rt.ibSystemStatus.fallbackHost}"'
            "  # CDN fallback for internet ping check"
        )
    )
    ibs.add(tomlkit.nl())
    ibs.add(
        tomlkit.comment(
            "Alert classification overrides (comma-separated, added to built-in lists):"
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_exchange_keywords = ""   '
            '# e.g., "PAXOS,COINBASE" — alerts mentioning these are non-blocking'
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_benign_phrases = ""      '
            '# e.g., "is resolved" — alerts matching these are non-blocking'
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_blocking_keywords = ""   '
            '# e.g., "emergency" — alerts matching these force CRITICAL severity'
        )
    )
    doc.add("ib_system_status", ibs)
    doc.add(tomlkit.nl())

    # [logging]
    log = tomlkit.table()
    log.add(tomlkit.comment('"debug", "info", "warn", or "error"'))
    log.add("level", rt.logging.level)
    log.add(tomlkit.comment("directory for persistent log files (set via IBCTL_LOG_DIR)"))
    log.add("log_dir", rt.logging.logDir)
    log.add(
        tomlkit.comment(
            "use futures market session dates for log filenames (env: IBCTL_FUTURES_SESSION_LOGGING)"
        )
    )
    log.add("futures_session_logging", rt.logging.futuresSessionLogging)
    log.add(
        tomlkit.comment(
            "hour (0-23 ET) when futures session reopens (env: IBCTL_SESSION_REOPEN_HOUR)"
        )
    )
    log.add("session_reopen_hour", int(rt.logging.sessionReopenHour))
    doc.add("logging", log)
    doc.add(tomlkit.nl())

    # [timing]
    tm = tomlkit.table()
    tm.add(tomlkit.comment("delay between UI actions in config dialog"))
    tm.add("ui_tick_ms", int(rt.timing.uiTickMs))
    tm.add(tomlkit.comment("Java agent delay after each Swing action"))
    tm.add("agent_tick_ms", int(rt.timing.agentTickMs))
    tm.add(tomlkit.comment("wait after login button before checking for 2FA"))
    tm.add("post_login_delay_ms", int(rt.timing.postLoginDelayMs))
    tm.add(tomlkit.comment("seconds of no popups before considering login complete"))
    tm.add("popup_quiet_secs", int(rt.timing.popupQuietSecs))
    tm.add(tomlkit.comment("max seconds to wait for popups"))
    tm.add("popup_max_wait_secs", int(rt.timing.popupMaxWaitSecs))
    tm.add(tomlkit.comment("pause after selecting radio buttons on login screen"))
    tm.add("login_radio_delay_ms", int(rt.timing.loginRadioDelayMs))
    tm.add(tomlkit.comment("SIGTERM wait before SIGKILL"))
    tm.add("jvm_shutdown_timeout_secs", int(rt.timing.jvmShutdownTimeoutSecs))
    tm.add(
        tomlkit.comment(
            "seconds to wait for login window (0 = wait indefinitely)"
        )
    )
    tm.add("login_dialog_timeout_secs", int(rt.timing.loginDialogTimeoutSecs))
    tm.add(tomlkit.comment("seconds to wait before restarting JVM after failure"))
    tm.add("restart_delay_secs", int(rt.timing.restartDelaySecs))
    tm.add(
        tomlkit.comment(
            "re-login attempts before cancel + restart JVM (0 = always cancel)"
        )
    )
    tm.add("relogin_max_attempts", int(rt.timing.reloginMaxAttempts))
    tm.add(
        tomlkit.comment(
            'action after exhausting re-login attempts: "reauth" or "restart" (env: IBCTL_RELOGIN_FAILURE_ACTION)'
        )
    )
    tm.add("relogin_failure_action", rt.timing.reloginFailureAction)
    tm.add(tomlkit.comment("TCP probe to Gateway API port during Connected; 0 = disabled"))
    tm.add("api_port_probe_interval_secs", int(rt.timing.apiPortProbeIntervalSecs))
    tm.add(tomlkit.comment("consecutive failures before revoking (absorbs OS-level blips)"))
    tm.add("api_port_probe_fails_before_revoke", int(rt.timing.apiPortProbeFailsBeforeRevoke))
    doc.add("timing", tm)
    doc.add(tomlkit.nl())

    # [site]
    site = tomlkit.table()
    site.add(tomlkit.comment('"primary" or "standby" (env: IBCTL_SITE_ROLE)'))
    site.add("role", cfg.deployment.siteRole)
    site.add(tomlkit.comment("auto-launch Gateway on startup (env: IBCTL_AUTO_LAUNCH)"))
    site.add("auto_launch", cfg.deployment.autoLaunch)
    doc.add("site", site)

    return tomlkit.dumps(doc)


def render_example_toml(cfg) -> str:
    """Render ibctl.toml.example — user-facing with guidance comments.

    Simpler than docker_toml: omits timing, dashboard, ib_system_status sections
    since those use code defaults. Includes more instructional comments.
    """
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by tools/generate_configs.py — DO NOT EDIT"))
    doc.add(tomlkit.comment("ibctl configuration file"))
    doc.add(tomlkit.comment(""))  # noqa: tomlkit adds trailing space
    doc.add(tomlkit.comment("Precedence (highest to lowest):"))
    doc.add(tomlkit.comment("  1. Environment variables (override everything)"))
    doc.add(tomlkit.comment("  2. This config file"))
    doc.add(tomlkit.comment("  3. Built-in defaults"))
    doc.add(tomlkit.comment(""))
    doc.add(
        tomlkit.comment(
            "Passwords and TOTP secrets are env-var only (with _FILE support)."
        )
    )
    doc.add(
        tomlkit.comment(
            "They are never read from this file to prevent committing secrets."
        )
    )
    doc.add(tomlkit.comment(""))
    doc.add(tomlkit.comment("Copy this file to ibctl.toml and edit as needed."))
    doc.add(tomlkit.nl())

    rt = cfg.runtime

    # [auth]
    auth = tomlkit.table()
    auth.add(tomlkit.comment("IB login username (env: TWS_USERID)"))
    auth.add("tws_userid", "")
    auth.add(tomlkit.comment("Trading mode: live | paper | both (env: TRADING_MODE)"))
    auth.add("trading_mode", rt.auth.tradingMode)
    doc.add("auth", auth)
    doc.add(tomlkit.nl())

    # [auth.paper]
    auth_paper = tomlkit.table()
    auth_paper.add(
        tomlkit.comment(
            "Paper account username, only needed for dual mode (env: TWS_USERID_PAPER)"
        )
    )
    auth_paper.add("tws_userid", "")
    # Use dotted key to get [auth.paper] not ["auth.paper"]
    auth["paper"] = auth_paper
    doc.add(tomlkit.nl())

    # [twofa]
    twofa = tomlkit.table()
    twofa.add(tomlkit.comment("TOTP provider: oathtool | builtin (env: TOTP_PROVIDER)"))
    twofa.add("provider", rt.twofa.provider)
    twofa.add(
        tomlkit.comment("Action on 2FA timeout: restart | exit (env: TWOFA_TIMEOUT_ACTION)")
    )
    twofa.add("timeout_action", rt.twofa.timeoutAction)
    twofa.add(
        tomlkit.comment(
            "Seconds to wait for 2FA completion (env: TWOFA_EXIT_INTERVAL)"
        )
    )
    # Example uses Rust code default (180), not Docker deployment default (120)
    twofa.add("exit_interval", 180)

    # [twofa.backoff] — HITL policy (nested sub-section)
    ex_backoff = tomlkit.table()
    ex_backoff.add(
        tomlkit.comment(
            "After this many consecutive 2FA timeouts, stop the tight restart loop"
        )
    )
    ex_backoff.add(
        tomlkit.comment("and enter WaitingForHitl2fa. 0 = disabled (loop forever).")
    )
    ex_backoff.add("max_immediate_attempts", int(rt.twofa.backoff.maxImmediateAttempts))
    ex_backoff.add(
        tomlkit.comment(
            '"restart_then_hitl" | "restart_forever" | "hitl_immediately"'
        )
    )
    ex_backoff.add("on_timeout", rt.twofa.backoff.onTimeout)
    ex_backoff.add(
        tomlkit.comment(
            'HITL strategy: "disabled" | "periodic" | "ntfy_callback" | "both"'
        )
    )
    ex_backoff.add("strategy", rt.twofa.backoff.strategy)
    ex_backoff.add(
        tomlkit.comment(
            "Retry cadence in minutes; list traversed then held at last value"
        )
    )
    ex_backoff.add(
        "intervals_minutes",
        [int(m) for m in _listing_to_list(rt.twofa.backoff.intervalsMinutes)],
    )
    ex_backoff.add(
        tomlkit.comment("ntfy action URL validity window (1..=168 hours)")
    )
    ex_backoff.add("callback_valid_hours", int(rt.twofa.backoff.callbackValidHours))
    ex_backoff.add(tomlkit.comment('"any_reach" | "stable" — when to reset the attempt counter'))
    ex_backoff.add("counter_reset", rt.twofa.backoff.counterReset)
    ex_backoff.add(tomlkit.comment("seconds Connected must persist under counter_reset=stable"))
    ex_backoff.add("stable_secs", int(rt.twofa.backoff.stableSecs))
    ex_backoff.add(
        tomlkit.comment("true: cold restart always interrupts HITL; false: defers")
    )
    ex_backoff.add("cold_restart_preempts_hitl", rt.twofa.backoff.coldRestartPreemptsHitl)
    ex_backoff.add(tomlkit.comment("retries for initial ntfy send failure (only with ntfy_callback/both)"))
    ex_backoff.add("ntfy_send_retries", int(rt.twofa.backoff.ntfySendRetries))
    ex_backoff.add(tomlkit.nl())
    ex_backoff.add(
        tomlkit.comment(
            "HMAC-SHA256 key for signing ntfy action URLs. Env only — never in TOML."
        )
    )
    ex_backoff.add(
        tomlkit.comment("# Env: IBCTL_NTFY_ACTION_SIGNING_KEY")
    )
    twofa.add("backoff", ex_backoff)
    doc.add("twofa", twofa)
    doc.add(tomlkit.nl())

    # [gateway]
    gw = tomlkit.table()
    gw.add(tomlkit.comment("Path to TWS/Gateway installation (env: TWS_PATH)"))
    gw.add("tws_path", rt.gateway.twsPath)
    gw.add(
        tomlkit.comment("Settings storage path, defaults to tws_path (env: TWS_SETTINGS_PATH)")
    )
    gw.add("tws_settings_path", "")
    gw.add(
        tomlkit.comment("Gateway version, auto-detected if empty (env: TWS_MAJOR_VRSN)")
    )
    gw.add("tws_major_vrsn", "")
    gw.add(tomlkit.comment("JVM heap size in MB (env: JAVA_HEAP_SIZE)"))
    gw.add("java_heap_size", int(rt.gateway.javaHeapSize))
    gw.add(tomlkit.comment("Program type: gateway | tws (env: GATEWAY_OR_TWS)"))
    gw.add("gateway_or_tws", rt.gateway.gatewayOrTws)
    doc.add("gateway", gw)
    doc.add(tomlkit.nl())

    # [session]
    sess = tomlkit.table()
    sess.add(
        tomlkit.comment(
            "Session conflict action: primary | secondary | primaryoverride"
            " (env: IBCTL_SESSION_ACTION)"
        )
    )
    sess.add("action", rt.session.action)
    sess.add(
        tomlkit.comment(
            "Incoming API connections: accept | reject | manual"
            " (env: IBCTL_ACCEPT_INCOMING)"
        )
    )
    sess.add("accept_incoming", rt.session.acceptIncoming)
    doc.add("session", sess)
    doc.add(tomlkit.nl())

    # [command_server]
    cs = tomlkit.table()
    cs.add(tomlkit.comment("Enable IBC-compatible TCP command server"))
    cs.add("enabled", rt.commandServer.enabled)
    cs.add(tomlkit.comment("TCP port (env: IBCTL_COMMAND_PORT)"))
    cs.add("port", int(rt.commandServer.port))
    cs.add(tomlkit.comment("Bind address"))
    cs.add("bind_address", rt.commandServer.bindAddress)
    cs.add(
        tomlkit.comment(
            "IP allow-list for command access (env: IBCTL_CONTROL_FROM, comma-separated)"
        )
    )
    # Example uses simpler control_from (localhost only, no Docker bridge)
    cs.add("control_from", ["127.0.0.1"])
    doc.add("command_server", cs)
    doc.add(tomlkit.nl())

    # [agent]
    agent = tomlkit.table()
    agent.add(
        tomlkit.comment(
            "Unix domain socket path for Rust<->Java agent IPC (env: IBCTL_AGENT_SOCKET)"
        )
    )
    # Example uses /tmp path (non-Docker), not /run/ibctl path (Docker)
    agent.add("socket_path", "/tmp/ibctl.sock")
    doc.add("agent", agent)
    doc.add(tomlkit.nl())

    # [ib_status]
    ibs_policy = tomlkit.table()
    ibs_policy.add(
        tomlkit.comment(
            "When IBSTATUS=unavailable arrives, should ibctl kick a Connected session?"
        )
    )
    ibs_policy.add(
        tomlkit.comment(
            "Default false — IBSTATUS gates login retry, not active sessions."
        )
    )
    ibs_policy.add("kick_active_session", rt.ibStatus.kickActiveSession)
    doc.add("ib_status", ibs_policy)
    doc.add(tomlkit.nl())

    # [logging]
    log = tomlkit.table()
    log.add(tomlkit.comment("Log level: debug | info | warn | error (env: IBCTL_LOG_LEVEL)"))
    log.add("level", rt.logging.level)
    doc.add("logging", log)
    doc.add(tomlkit.nl())

    # [timing]
    tm = tomlkit.table()
    tm.add(
        tomlkit.comment(
            "TCP probe interval to Gateway's API port during post-auth states."
        )
    )
    tm.add(
        tomlkit.comment(
            "0 = disabled (rely on label probe only). (env: IBCTL_API_PORT_PROBE_INTERVAL_SECS)"
        )
    )
    tm.add("api_port_probe_interval_secs", int(rt.timing.apiPortProbeIntervalSecs))
    tm.add(
        tomlkit.comment(
            "Consecutive TCP probe failures before firing ApiPortListenerLost revocation."
        )
    )
    tm.add(tomlkit.comment("(env: IBCTL_API_PORT_PROBE_FAILS_BEFORE_REVOKE)"))
    tm.add("api_port_probe_fails_before_revoke", int(rt.timing.apiPortProbeFailsBeforeRevoke))
    doc.add("timing", tm)

    return tomlkit.dumps(doc)
