"""Render ibctl TOML config files from evaluated Pkl config objects.

Two output modes:
- docker_toml: Full deployment defaults (docker/ibctl.toml) with all sections.
- example_toml: User-facing template (ibctl.toml.example) with guidance comments.
"""

from __future__ import annotations

import tomlkit


def _listing_to_list(obj) -> list:
    """Convert a Pkl Listing (or Python list) to a plain list."""
    if isinstance(obj, list):
        return obj
    # pkl-python may return lists directly; handle iterables
    try:
        return list(obj)
    except TypeError:
        return []


def render_docker_toml(cfg) -> str:
    """Render docker/ibctl.toml — rich deployment defaults with all sections.

    This matches the current docker/ibctl.toml layout and comments.
    """
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by tools/generate_configs.py — DO NOT EDIT"))
    doc.add(tomlkit.comment("ibctl configuration — defaults for Docker deployment"))
    doc.add(
        tomlkit.comment(
            "Override any value via environment variables (see docs/CLIENT_INTEGRATION_GUIDE.md)."
        )
    )
    doc.add(
        tomlkit.comment(
            "Passwords/secrets are NEVER in this file — use env vars (TWS_PASSWORD, etc.)"
        )
    )
    doc.add(tomlkit.nl())

    rt = cfg.runtime

    # [auth]
    auth = tomlkit.table()
    auth.add(tomlkit.comment("set via TWS_USERID env var"))
    auth.add("tws_userid", rt.auth.twsUserid)
    auth.add(tomlkit.comment('"live", "paper", or "both"'))
    auth.add("trading_mode", rt.auth.tradingMode)
    auth.add(tomlkit.comment("Paper credentials (for TRADING_MODE=both):"))
    auth.add(tomlkit.comment('paper.tws_userid = ""    # set via TWS_USERID_PAPER env var'))
    doc.add("auth", auth)
    doc.add(tomlkit.nl())

    # [twofa]
    twofa = tomlkit.table()
    twofa.add(
        tomlkit.comment(
            '"oathtool" (shells out) or "builtin" (not yet implemented)'
        )
    )
    twofa.add("provider", rt.twofa.provider)
    twofa.add(tomlkit.comment("name of env var holding TOTP secret"))
    twofa.add("secret_env", rt.twofa.secretEnv)
    twofa.add(tomlkit.comment('"restart" (re-login) or "exit" (shutdown)'))
    twofa.add("timeout_action", rt.twofa.timeoutAction)
    twofa.add(tomlkit.comment("max wait for 2FA approval before timeout_action"))
    twofa.add("exit_interval", int(rt.twofa.exitInterval))
    twofa.add(tomlkit.comment("2FA device name for device selection dialog (empty = skip)"))
    twofa.add("device", rt.twofa.device)
    twofa.add(tomlkit.comment("force re-login even if timeout_action != restart"))
    twofa.add("relogin_after_timeout", rt.twofa.reloginAfterTimeout)
    doc.add("twofa", twofa)
    doc.add(tomlkit.nl())

    # [gateway]
    gw = tomlkit.table()
    gw.add("tws_path", rt.gateway.twsPath)
    gw.add(tomlkit.comment("empty = use tws_path"))
    gw.add("tws_settings_path", rt.gateway.twsSettingsPath)
    gw.add(tomlkit.comment("auto-detected from TWS_MAJOR_VRSN env var"))
    gw.add("tws_major_vrsn", rt.gateway.twsMajorVrsn)
    gw.add("java_heap_size", int(rt.gateway.javaHeapSize))
    gw.add(tomlkit.comment('"gateway" or "tws"'))
    gw.add("gateway_or_tws", rt.gateway.gatewayOrTws)
    gw.add(
        tomlkit.comment(
            "API and socat port mappings (Gateway listens on api port, socat forwards from socat port)"
        )
    )
    gw.add("live_api_port", int(rt.gateway.liveApiPort))
    gw.add("paper_api_port", int(rt.gateway.paperApiPort))
    gw.add("live_socat_port", int(rt.gateway.liveSocatPort))
    gw.add("paper_socat_port", int(rt.gateway.paperSocatPort))
    doc.add("gateway", gw)
    doc.add(tomlkit.nl())

    # [session]
    sess = tomlkit.table()
    sess.add(tomlkit.comment('"primary", "secondary", or "primaryoverride"'))
    sess.add("action", rt.session.action)
    sess.add(tomlkit.comment('"accept", "reject", or "manual"'))
    sess.add("accept_incoming", rt.session.acceptIncoming)
    sess.add(tomlkit.comment('"HH:MM" 24h format for Sunday cold restart (empty = disabled)'))
    sess.add("tws_cold_restart", rt.session.twsColdRestart)
    doc.add("session", sess)
    doc.add(tomlkit.nl())

    # [command_server]
    cs = tomlkit.table()
    cs.add("enabled", rt.commandServer.enabled)
    cs.add(tomlkit.comment("live instance command server port"))
    cs.add("port", int(rt.commandServer.port))
    cs.add(tomlkit.comment("paper instance command server port"))
    cs.add("paper_port", int(rt.commandServer.paperPort))
    cs.add("bind_address", rt.commandServer.bindAddress)
    cs.add("control_from", _listing_to_list(rt.commandServer.controlFrom))
    doc.add("command_server", cs)
    doc.add(tomlkit.nl())

    # [agent]
    agent = tomlkit.table()
    agent.add("socket_path", rt.agent.socketPath)
    doc.add("agent", agent)
    doc.add(tomlkit.nl())

    # [dashboard]
    dash = tomlkit.table()
    dash.add(
        tomlkit.comment("set IBCTL_DASHBOARD_ENABLED=true to start the web dashboard")
    )
    dash.add("enabled", rt.dashboard.enabled)
    dash.add("port", int(rt.dashboard.port))
    dash.add(tomlkit.comment("Bearer token for API auth (empty = no auth)"))
    dash.add("token", "")
    dash.add(tomlkit.comment("enable debug endpoints"))
    dash.add("debug_mode", rt.dashboard.debugMode)
    doc.add("dashboard", dash)
    doc.add(tomlkit.nl())

    # [ib_system_status]
    ibs = tomlkit.table()
    ibs.add("enabled", rt.ibSystemStatus.enabled)
    ibs.add(
        tomlkit.comment(
            "fail-open TTL: if no status push within this period, assume available"
        )
    )
    ibs.add("ttl_seconds", int(rt.ibSystemStatus.ttlSeconds))
    ibs.add(
        tomlkit.comment(
            "Scraper settings (read by dashboard daemon, configurable via env vars too):"
        )
    )
    ibs.add(
        tomlkit.comment(
            f'check_interval = {int(rt.ibSystemStatus.checkIntervalSeconds)}'
            '     # seconds between IB status page scrapes (default 5 min)'
        )
    )
    ibs.add(
        tomlkit.comment(
            f'url = "{rt.ibSystemStatus.url}"'
        )
    )
    ibs.add(
        tomlkit.comment(
            f'region = "{rt.ibSystemStatus.region}"'
            '            # "NA", "EU", or "APAC" — which maintenance windows to monitor'
        )
    )
    backend_hosts_str = ",".join(_listing_to_list(rt.ibSystemStatus.backendHosts))
    ibs.add(
        tomlkit.comment(
            f'backend_hosts = "{backend_hosts_str}"'
            "  # IB backend servers (checked via ICMP ping)"
        )
    )
    ibs.add(
        tomlkit.comment(
            f'fallback_host = "{rt.ibSystemStatus.fallbackHost}"'
            "  # CDN fallback for internet ping check"
        )
    )
    ibs.add(tomlkit.nl())
    ibs.add(
        tomlkit.comment(
            "Alert classification overrides (comma-separated, added to built-in lists):"
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_exchange_keywords = ""   '
            '# e.g., "PAXOS,COINBASE" — alerts mentioning these are non-blocking'
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_benign_phrases = ""      '
            '# e.g., "is resolved" — alerts matching these are non-blocking'
        )
    )
    ibs.add(
        tomlkit.comment(
            'extra_blocking_keywords = ""   '
            '# e.g., "emergency" — alerts matching these force CRITICAL severity'
        )
    )
    doc.add("ib_system_status", ibs)
    doc.add(tomlkit.nl())

    # [logging]
    log = tomlkit.table()
    log.add(tomlkit.comment('"debug", "info", "warn", or "error"'))
    log.add("level", rt.logging.level)
    log.add(tomlkit.comment("directory for persistent log files (set via IBCTL_LOG_DIR)"))
    log.add("log_dir", rt.logging.logDir)
    doc.add("logging", log)
    doc.add(tomlkit.nl())

    # [timing]
    tm = tomlkit.table()
    tm.add(tomlkit.comment("delay between UI actions in config dialog"))
    tm.add("ui_tick_ms", int(rt.timing.uiTickMs))
    tm.add(tomlkit.comment("Java agent delay after each Swing action"))
    tm.add("agent_tick_ms", int(rt.timing.agentTickMs))
    tm.add(tomlkit.comment("wait after login button before checking for 2FA"))
    tm.add("post_login_delay_ms", int(rt.timing.postLoginDelayMs))
    tm.add(tomlkit.comment("seconds of no popups before considering login complete"))
    tm.add("popup_quiet_secs", int(rt.timing.popupQuietSecs))
    tm.add(tomlkit.comment("max seconds to wait for popups"))
    tm.add("popup_max_wait_secs", int(rt.timing.popupMaxWaitSecs))
    tm.add(tomlkit.comment("pause after selecting radio buttons on login screen"))
    tm.add("login_radio_delay_ms", int(rt.timing.loginRadioDelayMs))
    tm.add(tomlkit.comment("SIGTERM wait before SIGKILL"))
    tm.add("jvm_shutdown_timeout_secs", int(rt.timing.jvmShutdownTimeoutSecs))
    tm.add(
        tomlkit.comment(
            "seconds to wait for login window (0 = wait indefinitely)"
        )
    )
    tm.add("login_dialog_timeout_secs", int(rt.timing.loginDialogTimeoutSecs))
    tm.add(tomlkit.comment("seconds to wait before restarting JVM after failure"))
    tm.add("restart_delay_secs", int(rt.timing.restartDelaySecs))
    tm.add(
        tomlkit.comment(
            "re-login attempts before cancel + restart JVM (0 = always cancel)"
        )
    )
    tm.add("relogin_max_attempts", int(rt.timing.reloginMaxAttempts))
    doc.add("timing", tm)
    doc.add(tomlkit.nl())

    # [site]
    site = tomlkit.table()
    site.add(tomlkit.comment('"primary" or "standby" (env: IBCTL_SITE_ROLE)'))
    site.add("role", cfg.deployment.siteRole)
    site.add(tomlkit.comment("auto-launch Gateway on startup (env: IBCTL_AUTO_LAUNCH)"))
    site.add("auto_launch", cfg.deployment.autoLaunch)
    doc.add("site", site)

    return tomlkit.dumps(doc)


def render_example_toml(cfg) -> str:
    """Render ibctl.toml.example — user-facing with guidance comments.

    Simpler than docker_toml: omits timing, dashboard, ib_system_status sections
    since those use code defaults. Includes more instructional comments.
    """
    doc = tomlkit.document()
    doc.add(tomlkit.comment("Generated by tools/generate_configs.py — DO NOT EDIT"))
    doc.add(tomlkit.comment("ibctl configuration file"))
    doc.add(tomlkit.comment(""))  # noqa: tomlkit adds trailing space
    doc.add(tomlkit.comment("Precedence (highest to lowest):"))
    doc.add(tomlkit.comment("  1. Environment variables (override everything)"))
    doc.add(tomlkit.comment("  2. This config file"))
    doc.add(tomlkit.comment("  3. Built-in defaults"))
    doc.add(tomlkit.comment(""))
    doc.add(
        tomlkit.comment(
            "Passwords and TOTP secrets are env-var only (with _FILE support)."
        )
    )
    doc.add(
        tomlkit.comment(
            "They are never read from this file to prevent committing secrets."
        )
    )
    doc.add(tomlkit.comment(""))
    doc.add(tomlkit.comment("Copy this file to ibctl.toml and edit as needed."))
    doc.add(tomlkit.nl())

    rt = cfg.runtime

    # [auth]
    auth = tomlkit.table()
    auth.add(tomlkit.comment("IB login username (env: TWS_USERID)"))
    auth.add("tws_userid", "")
    auth.add(tomlkit.comment("Trading mode: live | paper | both (env: TRADING_MODE)"))
    auth.add("trading_mode", rt.auth.tradingMode)
    doc.add("auth", auth)
    doc.add(tomlkit.nl())

    # [auth.paper]
    auth_paper = tomlkit.table()
    auth_paper.add(
        tomlkit.comment(
            "Paper account username, only needed for dual mode (env: TWS_USERID_PAPER)"
        )
    )
    auth_paper.add("tws_userid", "")
    # Use dotted key to get [auth.paper] not ["auth.paper"]
    auth["paper"] = auth_paper
    doc.add(tomlkit.nl())

    # [twofa]
    twofa = tomlkit.table()
    twofa.add(tomlkit.comment("TOTP provider: oathtool | builtin (env: TOTP_PROVIDER)"))
    twofa.add("provider", rt.twofa.provider)
    twofa.add(
        tomlkit.comment("Action on 2FA timeout: restart | exit (env: TWOFA_TIMEOUT_ACTION)")
    )
    twofa.add("timeout_action", rt.twofa.timeoutAction)
    twofa.add(
        tomlkit.comment(
            "Seconds to wait for 2FA completion (env: TWOFA_EXIT_INTERVAL)"
        )
    )
    # Example uses Rust code default (180), not Docker deployment default (120)
    twofa.add("exit_interval", 180)
    doc.add("twofa", twofa)
    doc.add(tomlkit.nl())

    # [gateway]
    gw = tomlkit.table()
    gw.add(tomlkit.comment("Path to TWS/Gateway installation (env: TWS_PATH)"))
    gw.add("tws_path", rt.gateway.twsPath)
    gw.add(
        tomlkit.comment("Settings storage path, defaults to tws_path (env: TWS_SETTINGS_PATH)")
    )
    gw.add("tws_settings_path", "")
    gw.add(
        tomlkit.comment("Gateway version, auto-detected if empty (env: TWS_MAJOR_VRSN)")
    )
    gw.add("tws_major_vrsn", "")
    gw.add(tomlkit.comment("JVM heap size in MB (env: JAVA_HEAP_SIZE)"))
    gw.add("java_heap_size", int(rt.gateway.javaHeapSize))
    gw.add(tomlkit.comment("Program type: gateway | tws (env: GATEWAY_OR_TWS)"))
    gw.add("gateway_or_tws", rt.gateway.gatewayOrTws)
    doc.add("gateway", gw)
    doc.add(tomlkit.nl())

    # [session]
    sess = tomlkit.table()
    sess.add(
        tomlkit.comment(
            "Session conflict action: primary | secondary | primaryoverride"
            " (env: IBCTL_SESSION_ACTION)"
        )
    )
    sess.add("action", rt.session.action)
    sess.add(
        tomlkit.comment(
            "Incoming API connections: accept | reject | manual"
            " (env: IBCTL_ACCEPT_INCOMING)"
        )
    )
    sess.add("accept_incoming", rt.session.acceptIncoming)
    doc.add("session", sess)
    doc.add(tomlkit.nl())

    # [command_server]
    cs = tomlkit.table()
    cs.add(tomlkit.comment("Enable IBC-compatible TCP command server"))
    cs.add("enabled", rt.commandServer.enabled)
    cs.add(tomlkit.comment("TCP port (env: IBCTL_COMMAND_PORT)"))
    cs.add("port", int(rt.commandServer.port))
    cs.add(tomlkit.comment("Bind address"))
    cs.add("bind_address", rt.commandServer.bindAddress)
    cs.add(
        tomlkit.comment(
            "IP allow-list for command access (env: IBCTL_CONTROL_FROM, comma-separated)"
        )
    )
    # Example uses simpler control_from (localhost only, no Docker bridge)
    cs.add("control_from", ["127.0.0.1"])
    doc.add("command_server", cs)
    doc.add(tomlkit.nl())

    # [agent]
    agent = tomlkit.table()
    agent.add(
        tomlkit.comment(
            "Unix domain socket path for Rust<->Java agent IPC (env: IBCTL_AGENT_SOCKET)"
        )
    )
    # Example uses /tmp path (non-Docker), not /run/ibctl path (Docker)
    agent.add("socket_path", "/tmp/ibctl.sock")
    doc.add("agent", agent)
    doc.add(tomlkit.nl())

    # [logging]
    log = tomlkit.table()
    log.add(tomlkit.comment("Log level: debug | info | warn | error (env: IBCTL_LOG_LEVEL)"))
    log.add("level", rt.logging.level)
    doc.add("logging", log)

    return tomlkit.dumps(doc)
